# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  app.marvel_api_service:
    class:      AppBundle\Service\MarvelApiService
    arguments:  ['%marvel_api_key%']
  app.current_user_service:
    class:      AppBundle\Service\CurrentUserService
    arguments:  ['@security.token_storage']
  app.character_service:
      class:      AppBundle\Service\CharacterService
      arguments:  ['@doctrine.orm.entity_manager', '@app.current_user_service', '@app.repo.character']
  jwt_token_authenticator:
    class:      AppBundle\Security\JWTTokenAuthenticator
    autowire: true
  app.tokens.action_listener:
    class:      AppBundle\EventListener\CorsListener
    arguments: ['%app_bundle.cors.origins%']
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 300 }
  app.repo.character:
    class:      Doctrine\ORM\EntityRepository
    factory:    ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - AppBundle\Entity\MarvelCharacter
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
