<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MarvelCharacterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarvelCharacterRepository extends EntityRepository
{
    public function findByWithFavourite($user, array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {
        // Get characters
        $characters = parent::findBy($criteria, $orderBy, $limit, $offset);

        // Attach favourite values
        foreach ($characters as $character) {
            $character->setFavourite(123);
        }

        return $characters;
    }
}
